// This is a sample of GRPC -> S6a proxy for Diameter application S6a/S6d 3GPP 29.272
//
// For details about fields see:
// https://www.3gpp.org/dynareport/29272.htm

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: s6a.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BaseResultCode is a subset of Result-Code values from RFC 6733 section 7.1.
// Keep this namespace separate from vendor 10415 Experimental-Result-Code:
// e.g. base 5001 is AVP_UNSUPPORTED, whereas 3GPP 5001 is USER_UNKNOWN.
type BaseResultCode int32

const (
	BaseResultCode_BASE_UNDEFINED          BaseResultCode = 0
	BaseResultCode_MULTI_ROUND_AUTH        BaseResultCode = 1001
	BaseResultCode_SUCCESS                 BaseResultCode = 2001
	BaseResultCode_LIMITED_SUCCESS         BaseResultCode = 2002
	BaseResultCode_COMMAND_UNSUPPORTED     BaseResultCode = 3001
	BaseResultCode_UNABLE_TO_DELIVER       BaseResultCode = 3002
	BaseResultCode_REALM_NOT_SERVED        BaseResultCode = 3003
	BaseResultCode_TOO_BUSY                BaseResultCode = 3004
	BaseResultCode_LOOP_DETECTED           BaseResultCode = 3005
	BaseResultCode_REDIRECT_INDICATION     BaseResultCode = 3006
	BaseResultCode_APPLICATION_UNSUPPORTED BaseResultCode = 3007
	BaseResultCode_INVALID_HDR_BITS        BaseResultCode = 3008
	BaseResultCode_INVALID_AVP_BITS        BaseResultCode = 3009
	BaseResultCode_UNKNOWN_PEER            BaseResultCode = 3010
	BaseResultCode_AUTHENTICATION_REJECTED BaseResultCode = 4001
	BaseResultCode_OUT_OF_SPACE            BaseResultCode = 4002
	BaseResultCode_ELECTION_LOST           BaseResultCode = 4003
	// RFC 6733 section 7.1.5.
	BaseResultCode_AVP_UNSUPPORTED           BaseResultCode = 5001
	BaseResultCode_UNKNOWN_SESSION_ID        BaseResultCode = 5002
	BaseResultCode_AUTHORIZATION_REJECTED    BaseResultCode = 5003
	BaseResultCode_INVALID_AVP_VALUE         BaseResultCode = 5004
	BaseResultCode_MISSING_AVP               BaseResultCode = 5005
	BaseResultCode_RESOURCES_EXCEEDED        BaseResultCode = 5006
	BaseResultCode_CONTRADICTING_AVPS        BaseResultCode = 5007
	BaseResultCode_AVP_NOT_ALLOWED           BaseResultCode = 5008
	BaseResultCode_AVP_OCCURS_TOO_MANY_TIMES BaseResultCode = 5009
	BaseResultCode_NO_COMMON_APPLICATION     BaseResultCode = 5010
	BaseResultCode_UNSUPPORTED_VERSION       BaseResultCode = 5011
	BaseResultCode_UNABLE_TO_COMPLY          BaseResultCode = 5012
	BaseResultCode_INVALID_BIT_IN_HEADER     BaseResultCode = 5013
	BaseResultCode_INVALID_AVP_LENGTH        BaseResultCode = 5014
	BaseResultCode_INVALID_MESSAGE_LENGTH    BaseResultCode = 5015
	BaseResultCode_INVALID_AVP_BIT_COMBO     BaseResultCode = 5016
	BaseResultCode_NO_COMMON_SECURITY        BaseResultCode = 5017
)

// Enum value maps for BaseResultCode.
var (
	BaseResultCode_name = map[int32]string{
		0:    "BASE_UNDEFINED",
		1001: "MULTI_ROUND_AUTH",
		2001: "SUCCESS",
		2002: "LIMITED_SUCCESS",
		3001: "COMMAND_UNSUPPORTED",
		3002: "UNABLE_TO_DELIVER",
		3003: "REALM_NOT_SERVED",
		3004: "TOO_BUSY",
		3005: "LOOP_DETECTED",
		3006: "REDIRECT_INDICATION",
		3007: "APPLICATION_UNSUPPORTED",
		3008: "INVALID_HDR_BITS",
		3009: "INVALID_AVP_BITS",
		3010: "UNKNOWN_PEER",
		4001: "AUTHENTICATION_REJECTED",
		4002: "OUT_OF_SPACE",
		4003: "ELECTION_LOST",
		5001: "AVP_UNSUPPORTED",
		5002: "UNKNOWN_SESSION_ID",
		5003: "AUTHORIZATION_REJECTED",
		5004: "INVALID_AVP_VALUE",
		5005: "MISSING_AVP",
		5006: "RESOURCES_EXCEEDED",
		5007: "CONTRADICTING_AVPS",
		5008: "AVP_NOT_ALLOWED",
		5009: "AVP_OCCURS_TOO_MANY_TIMES",
		5010: "NO_COMMON_APPLICATION",
		5011: "UNSUPPORTED_VERSION",
		5012: "UNABLE_TO_COMPLY",
		5013: "INVALID_BIT_IN_HEADER",
		5014: "INVALID_AVP_LENGTH",
		5015: "INVALID_MESSAGE_LENGTH",
		5016: "INVALID_AVP_BIT_COMBO",
		5017: "NO_COMMON_SECURITY",
	}
	BaseResultCode_value = map[string]int32{
		"BASE_UNDEFINED":            0,
		"MULTI_ROUND_AUTH":          1001,
		"SUCCESS":                   2001,
		"LIMITED_SUCCESS":           2002,
		"COMMAND_UNSUPPORTED":       3001,
		"UNABLE_TO_DELIVER":         3002,
		"REALM_NOT_SERVED":          3003,
		"TOO_BUSY":                  3004,
		"LOOP_DETECTED":             3005,
		"REDIRECT_INDICATION":       3006,
		"APPLICATION_UNSUPPORTED":   3007,
		"INVALID_HDR_BITS":          3008,
		"INVALID_AVP_BITS":          3009,
		"UNKNOWN_PEER":              3010,
		"AUTHENTICATION_REJECTED":   4001,
		"OUT_OF_SPACE":              4002,
		"ELECTION_LOST":             4003,
		"AVP_UNSUPPORTED":           5001,
		"UNKNOWN_SESSION_ID":        5002,
		"AUTHORIZATION_REJECTED":    5003,
		"INVALID_AVP_VALUE":         5004,
		"MISSING_AVP":               5005,
		"RESOURCES_EXCEEDED":        5006,
		"CONTRADICTING_AVPS":        5007,
		"AVP_NOT_ALLOWED":           5008,
		"AVP_OCCURS_TOO_MANY_TIMES": 5009,
		"NO_COMMON_APPLICATION":     5010,
		"UNSUPPORTED_VERSION":       5011,
		"UNABLE_TO_COMPLY":          5012,
		"INVALID_BIT_IN_HEADER":     5013,
		"INVALID_AVP_LENGTH":        5014,
		"INVALID_MESSAGE_LENGTH":    5015,
		"INVALID_AVP_BIT_COMBO":     5016,
		"NO_COMMON_SECURITY":        5017,
	}
)

func (x BaseResultCode) Enum() *BaseResultCode {
	p := new(BaseResultCode)
	*p = x
	return p
}

func (x BaseResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_s6a_proto_enumTypes[0].Descriptor()
}

func (BaseResultCode) Type() protoreflect.EnumType {
	return &file_s6a_proto_enumTypes[0]
}

func (x BaseResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseResultCode.Descriptor instead.
func (BaseResultCode) EnumDescriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{0}
}

// Vendor 10415 Experimental-Result-Code values from 3GPP TS 29.272 V19.6.0
// sections 7.4.3 and 7.4.4. Base Result-Code failures are gRPC errors.
type ErrorCode int32

const (
	// No experimental result was received; this is not a Diameter result code.
	ErrorCode_UNDEFINED ErrorCode = 0
	// Permanent Failures 7.4.3
	ErrorCode_USER_UNKNOWN             ErrorCode = 5001
	ErrorCode_UNKNOWN_EPS_SUBSCRIPTION ErrorCode = 5420
	ErrorCode_RAT_NOT_ALLOWED          ErrorCode = 5421
	ErrorCode_ROAMING_NOT_ALLOWED      ErrorCode = 5004
	ErrorCode_EQUIPMENT_UNKNOWN        ErrorCode = 5422
	ErrorCode_UNKNOWN_SERVING_NODE     ErrorCode = 5423
	// Transient Failures 7.4.4
	ErrorCode_AUTHENTICATION_DATA_UNAVAILABLE ErrorCode = 4181
	// TS 29.272 V19.6.0 section 7.4.4.2.
	ErrorCode_CAMEL_SUBSCRIPTION_PRESENT ErrorCode = 4182
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "UNDEFINED",
		5001: "USER_UNKNOWN",
		5420: "UNKNOWN_EPS_SUBSCRIPTION",
		5421: "RAT_NOT_ALLOWED",
		5004: "ROAMING_NOT_ALLOWED",
		5422: "EQUIPMENT_UNKNOWN",
		5423: "UNKNOWN_SERVING_NODE",
		4181: "AUTHENTICATION_DATA_UNAVAILABLE",
		4182: "CAMEL_SUBSCRIPTION_PRESENT",
	}
	ErrorCode_value = map[string]int32{
		"UNDEFINED":                       0,
		"USER_UNKNOWN":                    5001,
		"UNKNOWN_EPS_SUBSCRIPTION":        5420,
		"RAT_NOT_ALLOWED":                 5421,
		"ROAMING_NOT_ALLOWED":             5004,
		"EQUIPMENT_UNKNOWN":               5422,
		"UNKNOWN_SERVING_NODE":            5423,
		"AUTHENTICATION_DATA_UNAVAILABLE": 4181,
		"CAMEL_SUBSCRIPTION_PRESENT":      4182,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_s6a_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_s6a_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{1}
}

type CancelLocationRequest_CancellationType int32

const (
	CancelLocationRequest_MME_UPDATE_PROCEDURE     CancelLocationRequest_CancellationType = 0
	CancelLocationRequest_SGSN_UPDATE_PROCEDURE    CancelLocationRequest_CancellationType = 1
	CancelLocationRequest_SUBSCRIPTION_WITHDRAWAL  CancelLocationRequest_CancellationType = 2
	CancelLocationRequest_UPDATE_PROCEDURE_IWF     CancelLocationRequest_CancellationType = 3
	CancelLocationRequest_INITIAL_ATTACH_PROCEDURE CancelLocationRequest_CancellationType = 4
	// TS 29.272 V19.6.0 section 7.3.24.
	CancelLocationRequest_DISASTER_CONDITION_TERMINATED CancelLocationRequest_CancellationType = 5
)

// Enum value maps for CancelLocationRequest_CancellationType.
var (
	CancelLocationRequest_CancellationType_name = map[int32]string{
		0: "MME_UPDATE_PROCEDURE",
		1: "SGSN_UPDATE_PROCEDURE",
		2: "SUBSCRIPTION_WITHDRAWAL",
		3: "UPDATE_PROCEDURE_IWF",
		4: "INITIAL_ATTACH_PROCEDURE",
		5: "DISASTER_CONDITION_TERMINATED",
	}
	CancelLocationRequest_CancellationType_value = map[string]int32{
		"MME_UPDATE_PROCEDURE":          0,
		"SGSN_UPDATE_PROCEDURE":         1,
		"SUBSCRIPTION_WITHDRAWAL":       2,
		"UPDATE_PROCEDURE_IWF":          3,
		"INITIAL_ATTACH_PROCEDURE":      4,
		"DISASTER_CONDITION_TERMINATED": 5,
	}
)

func (x CancelLocationRequest_CancellationType) Enum() *CancelLocationRequest_CancellationType {
	p := new(CancelLocationRequest_CancellationType)
	*p = x
	return p
}

func (x CancelLocationRequest_CancellationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelLocationRequest_CancellationType) Descriptor() protoreflect.EnumDescriptor {
	return file_s6a_proto_enumTypes[2].Descriptor()
}

func (CancelLocationRequest_CancellationType) Type() protoreflect.EnumType {
	return &file_s6a_proto_enumTypes[2]
}

func (x CancelLocationRequest_CancellationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelLocationRequest_CancellationType.Descriptor instead.
func (CancelLocationRequest_CancellationType) EnumDescriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{4, 0}
}

// Authentication Information Request (Section 7.2.5)
type AuthenticationInformationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IMSI in User-Name (TS 29.272 V19.6.0 clause 5 procedures).
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// Visited-PLMN-Id: three encoded MCC/MNC octets (section 7.3.9).
	VisitedPlmn []byte `protobuf:"bytes,2,opt,name=visited_plmn,json=visitedPlmn,proto3" json:"visited_plmn,omitempty"`
	// Number of vectors to request in response
	NumRequestedEutranVectors uint32 `protobuf:"varint,3,opt,name=num_requested_eutran_vectors,json=numRequestedEutranVectors,proto3" json:"num_requested_eutran_vectors,omitempty"`
	// Indicates to the HSS the values are requested for immediate attach
	ImmediateResponsePreferred bool `protobuf:"varint,4,opt,name=immediate_response_preferred,json=immediateResponsePreferred,proto3" json:"immediate_response_preferred,omitempty"`
	// Concatenation of RAND and AUTS in the case of a resync attach case
	ResyncInfo    []byte `protobuf:"bytes,5,opt,name=resync_info,json=resyncInfo,proto3" json:"resync_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationInformationRequest) Reset() {
	*x = AuthenticationInformationRequest{}
	mi := &file_s6a_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationInformationRequest) ProtoMessage() {}

func (x *AuthenticationInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationInformationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationInformationRequest) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationInformationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AuthenticationInformationRequest) GetVisitedPlmn() []byte {
	if x != nil {
		return x.VisitedPlmn
	}
	return nil
}

func (x *AuthenticationInformationRequest) GetNumRequestedEutranVectors() uint32 {
	if x != nil {
		return x.NumRequestedEutranVectors
	}
	return 0
}

func (x *AuthenticationInformationRequest) GetImmediateResponsePreferred() bool {
	if x != nil {
		return x.ImmediateResponsePreferred
	}
	return false
}

func (x *AuthenticationInformationRequest) GetResyncInfo() []byte {
	if x != nil {
		return x.ResyncInfo
	}
	return nil
}

// Authentication Information Answer (Section 7.2.6)
type AuthenticationInformationAnswer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EPC error code on failure
	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=ErrorCode" json:"error_code,omitempty"`
	// Available authentication vectors; fewer than requested may be returned (section 5.2.3.1.3).
	EutranVectors []*AuthenticationInformationAnswer_EUTRANVector `protobuf:"bytes,2,rep,name=eutran_vectors,json=eutranVectors,proto3" json:"eutran_vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationInformationAnswer) Reset() {
	*x = AuthenticationInformationAnswer{}
	mi := &file_s6a_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationInformationAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationInformationAnswer) ProtoMessage() {}

func (x *AuthenticationInformationAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationInformationAnswer.ProtoReflect.Descriptor instead.
func (*AuthenticationInformationAnswer) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationInformationAnswer) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_UNDEFINED
}

func (x *AuthenticationInformationAnswer) GetEutranVectors() []*AuthenticationInformationAnswer_EUTRANVector {
	if x != nil {
		return x.EutranVectors
	}
	return nil
}

// Update Location Request (Section 7.2.3)
type UpdateLocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IMSI in User-Name (TS 29.272 V19.6.0 clause 5 procedures).
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// Visited-PLMN-Id: three encoded MCC/MNC octets (section 7.3.9).
	VisitedPlmn []byte `protobuf:"bytes,2,opt,name=visited_plmn,json=visitedPlmn,proto3" json:"visited_plmn,omitempty"`
	// Selective unrolling of ULR-Flags 29.272 Table 7.3.7/1
	// Skip subscription data in response
	SkipSubscriberData bool `protobuf:"varint,3,opt,name=skip_subscriber_data,json=skipSubscriberData,proto3" json:"skip_subscriber_data,omitempty"` // bit 2
	// Send Cancel Location to other EPCs serving the UE
	InitialAttach bool `protobuf:"varint,4,opt,name=initial_attach,json=initialAttach,proto3" json:"initial_attach,omitempty"` // bit 5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_s6a_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateLocationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateLocationRequest) GetVisitedPlmn() []byte {
	if x != nil {
		return x.VisitedPlmn
	}
	return nil
}

func (x *UpdateLocationRequest) GetSkipSubscriberData() bool {
	if x != nil {
		return x.SkipSubscriberData
	}
	return false
}

func (x *UpdateLocationRequest) GetInitialAttach() bool {
	if x != nil {
		return x.InitialAttach
	}
	return false
}

// Update Location Answer (Section 7.2.4)
type UpdateLocationAnswer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EPC error code on failure
	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=ErrorCode" json:"error_code,omitempty"`
	// Identifier of the default APN
	DefaultContextId uint32 `protobuf:"varint,2,opt,name=default_context_id,json=defaultContextId,proto3" json:"default_context_id,omitempty"`
	// Subscriber authorized aggregate bitrate
	TotalAmbr *UpdateLocationAnswer_AggregatedMaximumBitrate `protobuf:"bytes,3,opt,name=total_ambr,json=totalAmbr,proto3" json:"total_ambr,omitempty"`
	// Indicates to wipe other stored APNs
	AllApnsIncluded bool `protobuf:"varint,4,opt,name=all_apns_included,json=allApnsIncluded,proto3" json:"all_apns_included,omitempty"`
	// APN configurations
	Apn           []*UpdateLocationAnswer_APNConfiguration `protobuf:"bytes,5,rep,name=apn,proto3" json:"apn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationAnswer) Reset() {
	*x = UpdateLocationAnswer{}
	mi := &file_s6a_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationAnswer) ProtoMessage() {}

func (x *UpdateLocationAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationAnswer.ProtoReflect.Descriptor instead.
func (*UpdateLocationAnswer) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLocationAnswer) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_UNDEFINED
}

func (x *UpdateLocationAnswer) GetDefaultContextId() uint32 {
	if x != nil {
		return x.DefaultContextId
	}
	return 0
}

func (x *UpdateLocationAnswer) GetTotalAmbr() *UpdateLocationAnswer_AggregatedMaximumBitrate {
	if x != nil {
		return x.TotalAmbr
	}
	return nil
}

func (x *UpdateLocationAnswer) GetAllApnsIncluded() bool {
	if x != nil {
		return x.AllApnsIncluded
	}
	return false
}

func (x *UpdateLocationAnswer) GetApn() []*UpdateLocationAnswer_APNConfiguration {
	if x != nil {
		return x.Apn
	}
	return nil
}

// Cancel Location Request (Section 7.2.7)
type CancelLocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IMSI in User-Name (TS 29.272 V19.6.0 clause 5 procedures).
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// Type of cancellation 7.3.24
	CancellationType CancelLocationRequest_CancellationType `protobuf:"varint,2,opt,name=cancellation_type,json=cancellationType,proto3,enum=CancelLocationRequest_CancellationType" json:"cancellation_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CancelLocationRequest) Reset() {
	*x = CancelLocationRequest{}
	mi := &file_s6a_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLocationRequest) ProtoMessage() {}

func (x *CancelLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLocationRequest.ProtoReflect.Descriptor instead.
func (*CancelLocationRequest) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{4}
}

func (x *CancelLocationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CancelLocationRequest) GetCancellationType() CancelLocationRequest_CancellationType {
	if x != nil {
		return x.CancellationType
	}
	return CancelLocationRequest_MME_UPDATE_PROCEDURE
}

// Cancel Location Answer (Section 7.2.8)
type CancelLocationAnswer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EPC error code on failure
	ErrorCode     ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLocationAnswer) Reset() {
	*x = CancelLocationAnswer{}
	mi := &file_s6a_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLocationAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLocationAnswer) ProtoMessage() {}

func (x *CancelLocationAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLocationAnswer.ProtoReflect.Descriptor instead.
func (*CancelLocationAnswer) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{5}
}

func (x *CancelLocationAnswer) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_UNDEFINED
}

// Purge UE Request (TS 29.272 V19.6.0 section 7.2.13)
type PurgeUERequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IMSI in User-Name (TS 29.272 V19.6.0 clause 5 procedures).
	UserName      string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeUERequest) Reset() {
	*x = PurgeUERequest{}
	mi := &file_s6a_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeUERequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeUERequest) ProtoMessage() {}

func (x *PurgeUERequest) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeUERequest.ProtoReflect.Descriptor instead.
func (*PurgeUERequest) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{6}
}

func (x *PurgeUERequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// Purge UE Answer (TS 29.272 V19.6.0 section 7.2.14)
type PurgeUEAnswer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EPC error code on failure
	ErrorCode     ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeUEAnswer) Reset() {
	*x = PurgeUEAnswer{}
	mi := &file_s6a_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeUEAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeUEAnswer) ProtoMessage() {}

func (x *PurgeUEAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeUEAnswer.ProtoReflect.Descriptor instead.
func (*PurgeUEAnswer) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{7}
}

func (x *PurgeUEAnswer) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_UNDEFINED
}

// Reset Request (3GPP TS 29.272 Section 7.2.15)
type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Leading IMSI digits identifying subscriber sets (section 7.3.50).
	UserId        []string `protobuf:"bytes,1,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_s6a_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{8}
}

func (x *ResetRequest) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

// Reset Answer (3GPP TS 29.272 Section 7.2.16)
type ResetAnswer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EPC error code on failure
	ErrorCode     ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAnswer) Reset() {
	*x = ResetAnswer{}
	mi := &file_s6a_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAnswer) ProtoMessage() {}

func (x *ResetAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAnswer.ProtoReflect.Descriptor instead.
func (*ResetAnswer) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{9}
}

func (x *ResetAnswer) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_UNDEFINED
}

// For details about fields read 3GPP 33.401
type AuthenticationInformationAnswer_EUTRANVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rand          []byte                 `protobuf:"bytes,1,opt,name=rand,proto3" json:"rand,omitempty"`
	Xres          []byte                 `protobuf:"bytes,2,opt,name=xres,proto3" json:"xres,omitempty"`
	Autn          []byte                 `protobuf:"bytes,3,opt,name=autn,proto3" json:"autn,omitempty"`
	Kasme         []byte                 `protobuf:"bytes,4,opt,name=kasme,proto3" json:"kasme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationInformationAnswer_EUTRANVector) Reset() {
	*x = AuthenticationInformationAnswer_EUTRANVector{}
	mi := &file_s6a_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationInformationAnswer_EUTRANVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationInformationAnswer_EUTRANVector) ProtoMessage() {}

func (x *AuthenticationInformationAnswer_EUTRANVector) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationInformationAnswer_EUTRANVector.ProtoReflect.Descriptor instead.
func (*AuthenticationInformationAnswer_EUTRANVector) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AuthenticationInformationAnswer_EUTRANVector) GetRand() []byte {
	if x != nil {
		return x.Rand
	}
	return nil
}

func (x *AuthenticationInformationAnswer_EUTRANVector) GetXres() []byte {
	if x != nil {
		return x.Xres
	}
	return nil
}

func (x *AuthenticationInformationAnswer_EUTRANVector) GetAutn() []byte {
	if x != nil {
		return x.Autn
	}
	return nil
}

func (x *AuthenticationInformationAnswer_EUTRANVector) GetKasme() []byte {
	if x != nil {
		return x.Kasme
	}
	return nil
}

type UpdateLocationAnswer_APNConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// APN identifier
	ContextId uint32 `protobuf:"varint,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// Contains either the APN Name or wildcard "*"
	ServiceSelection string `protobuf:"bytes,2,opt,name=service_selection,json=serviceSelection,proto3" json:"service_selection,omitempty"`
	// APN QoS profile
	QosProfile *UpdateLocationAnswer_APNConfiguration_QoSProfile `protobuf:"bytes,3,opt,name=qos_profile,json=qosProfile,proto3" json:"qos_profile,omitempty"`
	// APN authorized bitrate
	Ambr          *UpdateLocationAnswer_AggregatedMaximumBitrate `protobuf:"bytes,4,opt,name=ambr,proto3" json:"ambr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationAnswer_APNConfiguration) Reset() {
	*x = UpdateLocationAnswer_APNConfiguration{}
	mi := &file_s6a_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationAnswer_APNConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationAnswer_APNConfiguration) ProtoMessage() {}

func (x *UpdateLocationAnswer_APNConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationAnswer_APNConfiguration.ProtoReflect.Descriptor instead.
func (*UpdateLocationAnswer_APNConfiguration) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UpdateLocationAnswer_APNConfiguration) GetContextId() uint32 {
	if x != nil {
		return x.ContextId
	}
	return 0
}

func (x *UpdateLocationAnswer_APNConfiguration) GetServiceSelection() string {
	if x != nil {
		return x.ServiceSelection
	}
	return ""
}

func (x *UpdateLocationAnswer_APNConfiguration) GetQosProfile() *UpdateLocationAnswer_APNConfiguration_QoSProfile {
	if x != nil {
		return x.QosProfile
	}
	return nil
}

func (x *UpdateLocationAnswer_APNConfiguration) GetAmbr() *UpdateLocationAnswer_AggregatedMaximumBitrate {
	if x != nil {
		return x.Ambr
	}
	return nil
}

type UpdateLocationAnswer_AggregatedMaximumBitrate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum uplink bitrate in bits/s (section 7.3.41).
	MaxBandwidthUl uint32 `protobuf:"varint,1,opt,name=max_bandwidth_ul,json=maxBandwidthUl,proto3" json:"max_bandwidth_ul,omitempty"`
	// Maximum downlink bitrate in bits/s (section 7.3.41).
	MaxBandwidthDl uint32 `protobuf:"varint,2,opt,name=max_bandwidth_dl,json=maxBandwidthDl,proto3" json:"max_bandwidth_dl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLocationAnswer_AggregatedMaximumBitrate) Reset() {
	*x = UpdateLocationAnswer_AggregatedMaximumBitrate{}
	mi := &file_s6a_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationAnswer_AggregatedMaximumBitrate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationAnswer_AggregatedMaximumBitrate) ProtoMessage() {}

func (x *UpdateLocationAnswer_AggregatedMaximumBitrate) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationAnswer_AggregatedMaximumBitrate.ProtoReflect.Descriptor instead.
func (*UpdateLocationAnswer_AggregatedMaximumBitrate) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{3, 1}
}

func (x *UpdateLocationAnswer_AggregatedMaximumBitrate) GetMaxBandwidthUl() uint32 {
	if x != nil {
		return x.MaxBandwidthUl
	}
	return 0
}

func (x *UpdateLocationAnswer_AggregatedMaximumBitrate) GetMaxBandwidthDl() uint32 {
	if x != nil {
		return x.MaxBandwidthDl
	}
	return 0
}

// For details about values see 29.212
type UpdateLocationAnswer_APNConfiguration_QoSProfile struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ClassId                 int32                  `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	PriorityLevel           uint32                 `protobuf:"varint,2,opt,name=priority_level,json=priorityLevel,proto3" json:"priority_level,omitempty"`
	PreemptionCapability    bool                   `protobuf:"varint,3,opt,name=preemption_capability,json=preemptionCapability,proto3" json:"preemption_capability,omitempty"`
	PreemptionVulnerability bool                   `protobuf:"varint,4,opt,name=preemption_vulnerability,json=preemptionVulnerability,proto3" json:"preemption_vulnerability,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateLocationAnswer_APNConfiguration_QoSProfile) Reset() {
	*x = UpdateLocationAnswer_APNConfiguration_QoSProfile{}
	mi := &file_s6a_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationAnswer_APNConfiguration_QoSProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationAnswer_APNConfiguration_QoSProfile) ProtoMessage() {}

func (x *UpdateLocationAnswer_APNConfiguration_QoSProfile) ProtoReflect() protoreflect.Message {
	mi := &file_s6a_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationAnswer_APNConfiguration_QoSProfile.ProtoReflect.Descriptor instead.
func (*UpdateLocationAnswer_APNConfiguration_QoSProfile) Descriptor() ([]byte, []int) {
	return file_s6a_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *UpdateLocationAnswer_APNConfiguration_QoSProfile) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *UpdateLocationAnswer_APNConfiguration_QoSProfile) GetPriorityLevel() uint32 {
	if x != nil {
		return x.PriorityLevel
	}
	return 0
}

func (x *UpdateLocationAnswer_APNConfiguration_QoSProfile) GetPreemptionCapability() bool {
	if x != nil {
		return x.PreemptionCapability
	}
	return false
}

func (x *UpdateLocationAnswer_APNConfiguration_QoSProfile) GetPreemptionVulnerability() bool {
	if x != nil {
		return x.PreemptionVulnerability
	}
	return false
}

var File_s6a_proto protoreflect.FileDescriptor

const file_s6a_proto_rawDesc = "" +
	"\n" +
	"\ts6a.proto\"\x86\x02\n" +
	" AuthenticationInformationRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12!\n" +
	"\fvisited_plmn\x18\x02 \x01(\fR\vvisitedPlmn\x12?\n" +
	"\x1cnum_requested_eutran_vectors\x18\x03 \x01(\rR\x19numRequestedEutranVectors\x12@\n" +
	"\x1cimmediate_response_preferred\x18\x04 \x01(\bR\x1aimmediateResponsePreferred\x12\x1f\n" +
	"\vresync_info\x18\x05 \x01(\fR\n" +
	"resyncInfo\"\x84\x02\n" +
	"\x1fAuthenticationInformationAnswer\x12)\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\n" +
	".ErrorCodeR\terrorCode\x12T\n" +
	"\x0eeutran_vectors\x18\x02 \x03(\v2-.AuthenticationInformationAnswer.EUTRANVectorR\reutranVectors\x1a`\n" +
	"\fEUTRANVector\x12\x12\n" +
	"\x04rand\x18\x01 \x01(\fR\x04rand\x12\x12\n" +
	"\x04xres\x18\x02 \x01(\fR\x04xres\x12\x12\n" +
	"\x04autn\x18\x03 \x01(\fR\x04autn\x12\x14\n" +
	"\x05kasme\x18\x04 \x01(\fR\x05kasme\"\xb0\x01\n" +
	"\x15UpdateLocationRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12!\n" +
	"\fvisited_plmn\x18\x02 \x01(\fR\vvisitedPlmn\x120\n" +
	"\x14skip_subscriber_data\x18\x03 \x01(\bR\x12skipSubscriberData\x12%\n" +
	"\x0einitial_attach\x18\x04 \x01(\bR\rinitialAttach\"\xce\x06\n" +
	"\x14UpdateLocationAnswer\x12)\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\n" +
	".ErrorCodeR\terrorCode\x12,\n" +
	"\x12default_context_id\x18\x02 \x01(\rR\x10defaultContextId\x12M\n" +
	"\n" +
	"total_ambr\x18\x03 \x01(\v2..UpdateLocationAnswer.AggregatedMaximumBitrateR\ttotalAmbr\x12*\n" +
	"\x11all_apns_included\x18\x04 \x01(\bR\x0fallApnsIncluded\x128\n" +
	"\x03apn\x18\x05 \x03(\v2&.UpdateLocationAnswer.APNConfigurationR\x03apn\x1a\xb7\x03\n" +
	"\x10APNConfiguration\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\rR\tcontextId\x12+\n" +
	"\x11service_selection\x18\x02 \x01(\tR\x10serviceSelection\x12R\n" +
	"\vqos_profile\x18\x03 \x01(\v21.UpdateLocationAnswer.APNConfiguration.QoSProfileR\n" +
	"qosProfile\x12B\n" +
	"\x04ambr\x18\x04 \x01(\v2..UpdateLocationAnswer.AggregatedMaximumBitrateR\x04ambr\x1a\xbe\x01\n" +
	"\n" +
	"QoSProfile\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\x05R\aclassId\x12%\n" +
	"\x0epriority_level\x18\x02 \x01(\rR\rpriorityLevel\x123\n" +
	"\x15preemption_capability\x18\x03 \x01(\bR\x14preemptionCapability\x129\n" +
	"\x18preemption_vulnerability\x18\x04 \x01(\bR\x17preemptionVulnerability\x1an\n" +
	"\x18AggregatedMaximumBitrate\x12(\n" +
	"\x10max_bandwidth_ul\x18\x01 \x01(\rR\x0emaxBandwidthUl\x12(\n" +
	"\x10max_bandwidth_dl\x18\x02 \x01(\rR\x0emaxBandwidthDl\"\xcc\x02\n" +
	"\x15CancelLocationRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12T\n" +
	"\x11cancellation_type\x18\x02 \x01(\x0e2'.CancelLocationRequest.CancellationTypeR\x10cancellationType\"\xbf\x01\n" +
	"\x10CancellationType\x12\x18\n" +
	"\x14MME_UPDATE_PROCEDURE\x10\x00\x12\x19\n" +
	"\x15SGSN_UPDATE_PROCEDURE\x10\x01\x12\x1b\n" +
	"\x17SUBSCRIPTION_WITHDRAWAL\x10\x02\x12\x18\n" +
	"\x14UPDATE_PROCEDURE_IWF\x10\x03\x12\x1c\n" +
	"\x18INITIAL_ATTACH_PROCEDURE\x10\x04\x12!\n" +
	"\x1dDISASTER_CONDITION_TERMINATED\x10\x05\"A\n" +
	"\x14CancelLocationAnswer\x12)\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\n" +
	".ErrorCodeR\terrorCode\"-\n" +
	"\x0ePurgeUERequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\":\n" +
	"\rPurgeUEAnswer\x12)\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\n" +
	".ErrorCodeR\terrorCode\"'\n" +
	"\fResetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x03(\tR\x06userId\"8\n" +
	"\vResetAnswer\x12)\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\n" +
	".ErrorCodeR\terrorCode*\xbb\x06\n" +
	"\x0eBaseResultCode\x12\x12\n" +
	"\x0eBASE_UNDEFINED\x10\x00\x12\x15\n" +
	"\x10MULTI_ROUND_AUTH\x10\xe9\a\x12\f\n" +
	"\aSUCCESS\x10\xd1\x0f\x12\x14\n" +
	"\x0fLIMITED_SUCCESS\x10\xd2\x0f\x12\x18\n" +
	"\x13COMMAND_UNSUPPORTED\x10\xb9\x17\x12\x16\n" +
	"\x11UNABLE_TO_DELIVER\x10\xba\x17\x12\x15\n" +
	"\x10REALM_NOT_SERVED\x10\xbb\x17\x12\r\n" +
	"\bTOO_BUSY\x10\xbc\x17\x12\x12\n" +
	"\rLOOP_DETECTED\x10\xbd\x17\x12\x18\n" +
	"\x13REDIRECT_INDICATION\x10\xbe\x17\x12\x1c\n" +
	"\x17APPLICATION_UNSUPPORTED\x10\xbf\x17\x12\x15\n" +
	"\x10INVALID_HDR_BITS\x10\xc0\x17\x12\x15\n" +
	"\x10INVALID_AVP_BITS\x10\xc1\x17\x12\x11\n" +
	"\fUNKNOWN_PEER\x10\xc2\x17\x12\x1c\n" +
	"\x17AUTHENTICATION_REJECTED\x10\xa1\x1f\x12\x11\n" +
	"\fOUT_OF_SPACE\x10\xa2\x1f\x12\x12\n" +
	"\rELECTION_LOST\x10\xa3\x1f\x12\x14\n" +
	"\x0fAVP_UNSUPPORTED\x10\x89'\x12\x17\n" +
	"\x12UNKNOWN_SESSION_ID\x10\x8a'\x12\x1b\n" +
	"\x16AUTHORIZATION_REJECTED\x10\x8b'\x12\x16\n" +
	"\x11INVALID_AVP_VALUE\x10\x8c'\x12\x10\n" +
	"\vMISSING_AVP\x10\x8d'\x12\x17\n" +
	"\x12RESOURCES_EXCEEDED\x10\x8e'\x12\x17\n" +
	"\x12CONTRADICTING_AVPS\x10\x8f'\x12\x14\n" +
	"\x0fAVP_NOT_ALLOWED\x10\x90'\x12\x1e\n" +
	"\x19AVP_OCCURS_TOO_MANY_TIMES\x10\x91'\x12\x1a\n" +
	"\x15NO_COMMON_APPLICATION\x10\x92'\x12\x18\n" +
	"\x13UNSUPPORTED_VERSION\x10\x93'\x12\x15\n" +
	"\x10UNABLE_TO_COMPLY\x10\x94'\x12\x1a\n" +
	"\x15INVALID_BIT_IN_HEADER\x10\x95'\x12\x17\n" +
	"\x12INVALID_AVP_LENGTH\x10\x96'\x12\x1b\n" +
	"\x16INVALID_MESSAGE_LENGTH\x10\x97'\x12\x1a\n" +
	"\x15INVALID_AVP_BIT_COMBO\x10\x98'\x12\x17\n" +
	"\x12NO_COMMON_SECURITY\x10\x99'*\xf6\x01\n" +
	"\tErrorCode\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\x11\n" +
	"\fUSER_UNKNOWN\x10\x89'\x12\x1d\n" +
	"\x18UNKNOWN_EPS_SUBSCRIPTION\x10\xac*\x12\x14\n" +
	"\x0fRAT_NOT_ALLOWED\x10\xad*\x12\x18\n" +
	"\x13ROAMING_NOT_ALLOWED\x10\x8c'\x12\x16\n" +
	"\x11EQUIPMENT_UNKNOWN\x10\xae*\x12\x19\n" +
	"\x14UNKNOWN_SERVING_NODE\x10\xaf*\x12$\n" +
	"\x1fAUTHENTICATION_DATA_UNAVAILABLE\x10\xd5 \x12\x1f\n" +
	"\x1aCAMEL_SUBSCRIPTION_PRESENT\x10\xd6 2\xca\x02\n" +
	"\bS6aProxy\x12b\n" +
	"\x19AuthenticationInformation\x12!.AuthenticationInformationRequest\x1a .AuthenticationInformationAnswer\"\x00\x12A\n" +
	"\x0eUpdateLocation\x12\x16.UpdateLocationRequest\x1a\x15.UpdateLocationAnswer\"\x00\x12A\n" +
	"\x0eCancelLocation\x12\x16.CancelLocationRequest\x1a\x15.CancelLocationAnswer\"\x00\x12,\n" +
	"\aPurgeUE\x12\x0f.PurgeUERequest\x1a\x0e.PurgeUEAnswer\"\x00\x12&\n" +
	"\x05Reset\x12\r.ResetRequest\x1a\f.ResetAnswer\"\x00B9Z7github.com/gomaja/go-diameter/examples/s6a_proxy/protosb\x06proto3"

var (
	file_s6a_proto_rawDescOnce sync.Once
	file_s6a_proto_rawDescData []byte
)

func file_s6a_proto_rawDescGZIP() []byte {
	file_s6a_proto_rawDescOnce.Do(func() {
		file_s6a_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s6a_proto_rawDesc), len(file_s6a_proto_rawDesc)))
	})
	return file_s6a_proto_rawDescData
}

var file_s6a_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_s6a_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_s6a_proto_goTypes = []any{
	(BaseResultCode)(0), // 0: BaseResultCode
	(ErrorCode)(0),      // 1: ErrorCode
	(CancelLocationRequest_CancellationType)(0),              // 2: CancelLocationRequest.CancellationType
	(*AuthenticationInformationRequest)(nil),                 // 3: AuthenticationInformationRequest
	(*AuthenticationInformationAnswer)(nil),                  // 4: AuthenticationInformationAnswer
	(*UpdateLocationRequest)(nil),                            // 5: UpdateLocationRequest
	(*UpdateLocationAnswer)(nil),                             // 6: UpdateLocationAnswer
	(*CancelLocationRequest)(nil),                            // 7: CancelLocationRequest
	(*CancelLocationAnswer)(nil),                             // 8: CancelLocationAnswer
	(*PurgeUERequest)(nil),                                   // 9: PurgeUERequest
	(*PurgeUEAnswer)(nil),                                    // 10: PurgeUEAnswer
	(*ResetRequest)(nil),                                     // 11: ResetRequest
	(*ResetAnswer)(nil),                                      // 12: ResetAnswer
	(*AuthenticationInformationAnswer_EUTRANVector)(nil),     // 13: AuthenticationInformationAnswer.EUTRANVector
	(*UpdateLocationAnswer_APNConfiguration)(nil),            // 14: UpdateLocationAnswer.APNConfiguration
	(*UpdateLocationAnswer_AggregatedMaximumBitrate)(nil),    // 15: UpdateLocationAnswer.AggregatedMaximumBitrate
	(*UpdateLocationAnswer_APNConfiguration_QoSProfile)(nil), // 16: UpdateLocationAnswer.APNConfiguration.QoSProfile
}
var file_s6a_proto_depIdxs = []int32{
	1,  // 0: AuthenticationInformationAnswer.error_code:type_name -> ErrorCode
	13, // 1: AuthenticationInformationAnswer.eutran_vectors:type_name -> AuthenticationInformationAnswer.EUTRANVector
	1,  // 2: UpdateLocationAnswer.error_code:type_name -> ErrorCode
	15, // 3: UpdateLocationAnswer.total_ambr:type_name -> UpdateLocationAnswer.AggregatedMaximumBitrate
	14, // 4: UpdateLocationAnswer.apn:type_name -> UpdateLocationAnswer.APNConfiguration
	2,  // 5: CancelLocationRequest.cancellation_type:type_name -> CancelLocationRequest.CancellationType
	1,  // 6: CancelLocationAnswer.error_code:type_name -> ErrorCode
	1,  // 7: PurgeUEAnswer.error_code:type_name -> ErrorCode
	1,  // 8: ResetAnswer.error_code:type_name -> ErrorCode
	16, // 9: UpdateLocationAnswer.APNConfiguration.qos_profile:type_name -> UpdateLocationAnswer.APNConfiguration.QoSProfile
	15, // 10: UpdateLocationAnswer.APNConfiguration.ambr:type_name -> UpdateLocationAnswer.AggregatedMaximumBitrate
	3,  // 11: S6aProxy.AuthenticationInformation:input_type -> AuthenticationInformationRequest
	5,  // 12: S6aProxy.UpdateLocation:input_type -> UpdateLocationRequest
	7,  // 13: S6aProxy.CancelLocation:input_type -> CancelLocationRequest
	9,  // 14: S6aProxy.PurgeUE:input_type -> PurgeUERequest
	11, // 15: S6aProxy.Reset:input_type -> ResetRequest
	4,  // 16: S6aProxy.AuthenticationInformation:output_type -> AuthenticationInformationAnswer
	6,  // 17: S6aProxy.UpdateLocation:output_type -> UpdateLocationAnswer
	8,  // 18: S6aProxy.CancelLocation:output_type -> CancelLocationAnswer
	10, // 19: S6aProxy.PurgeUE:output_type -> PurgeUEAnswer
	12, // 20: S6aProxy.Reset:output_type -> ResetAnswer
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_s6a_proto_init() }
func file_s6a_proto_init() {
	if File_s6a_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s6a_proto_rawDesc), len(file_s6a_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s6a_proto_goTypes,
		DependencyIndexes: file_s6a_proto_depIdxs,
		EnumInfos:         file_s6a_proto_enumTypes,
		MessageInfos:      file_s6a_proto_msgTypes,
	}.Build()
	File_s6a_proto = out.File
	file_s6a_proto_goTypes = nil
	file_s6a_proto_depIdxs = nil
}
